.TH "algoType" 3 "Fri Mar 17 2017" "Version 1" "targeter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
algoType
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBalgoType\fP { \fBCOOC\fP, \fBLAPLACIAN\fP, \fBSQDIFF\fP, \fBSQDIFF_NORMED\fP, \fBCCORR\fP, \fBCCORR_NORMED\fP, \fBCCOEFF\fP, \fBCCOEFF_NORMED\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
enum to set algorithm type for target detection 
.SH "Author"
.PP 
Generated automatically by Doxygen for targeter from the source code\&.
