.TH "drawingMode" 3 "Fri Mar 17 2017" "Version 1" "targeter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drawingMode
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBdrawingMode\fP { \fBrect\fP, \fBpoly\fP, \fBcircle\fP, \fBnone\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
enum to set drawing mode of drawing object 
.SH "Author"
.PP 
Generated automatically by Doxygen for targeter from the source code\&.
