.TH "drawingShape" 3 "Fri Mar 17 2017" "Version 1" "targeter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
drawingShape
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <globals\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBprintDebug\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QRect \fBboundingBox\fP"
.br
.ti -1c
.RI "drawingMode::drawingMode \fBtype\fP"
.br
.ti -1c
.RI "QPolygon \fBpolygon\fP"
.br
.ti -1c
.RI "int \fBradius\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
structure to represent shape being drawn 
.PP
Definition at line 218 of file globals\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for targeter from the source code\&.
