.TH "entropyCluster" 3 "Fri Mar 17 2017" "Version 1" "targeter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
entropyCluster
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBprintMe\fP (std::string s='')"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBfreq\fP"
.br
.ti -1c
.RI "std::vector< int > \fBhueList\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 199 of file globals\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for targeter from the source code\&.
