.TH "histCluster" 3 "Fri Mar 17 2017" "Version 1" "targeter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
histCluster
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <globals\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBprintMe\fP (std::string s='')"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBhistogramBar\fP > \fBcolumn\fP"
.br
.ti -1c
.RI "float \fBvarHue\fP"
.br
.RI "each histogram column as vector "
.ti -1c
.RI "float \fBmeanHue\fP"
.br
.RI "variance "
.ti -1c
.RI "std::vector< int > \fBhueList\fP"
.br
.RI "mean "
.in -1c
.SH "Detailed Description"
.PP 
structure to represent vector of histogram bars, ie\&. whole histogram 
.PP
Definition at line 172 of file globals\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for targeter from the source code\&.
