.TH "histogramBar" 3 "Fri Mar 17 2017" "Version 1" "targeter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
histogramBar
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <globals\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBprintMe\fP (std::string s='')"
.br
.RI "position of histogram (hue or grayscale) "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBfreq\fP"
.br
.ti -1c
.RI "double \fBhue\fP"
.br
.RI "count of histogram (normalised) "
.in -1c
.SH "Detailed Description"
.PP 
structure to represent histogram bar 
.PP
Definition at line 159 of file globals\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for targeter from the source code\&.
