.TH "imageType" 3 "Fri Mar 17 2017" "Version 1" "targeter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
imageType
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBimageType\fP { \fBdisplay\fP, \fBtarget\fP, \fBtest\fP, \fBmask\fP, \fBroi\fP, \fBcclabels\fP, \fBscore\fP, \fBcentroids\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
enum to set type of image 
.SH "Author"
.PP 
Generated automatically by Doxygen for targeter from the source code\&.
