.TH "MergeSettingsDialog" 3 "Fri Mar 17 2017" "Version 1" "targeter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MergeSettingsDialog
.SH SYNOPSIS
.br
.PP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMergeSettingsDialog\fP (QWidget *parent=0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file mergesettingsdialog\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for targeter from the source code\&.
