.TH "OpenCVtrilateralFilter" 3 "Fri Mar 17 2017" "Version 1" "targeter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpenCVtrilateralFilter
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBTYPE_LUT\fP, \fBTYPE_FAST\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBtrilateralFilter\fP (cv::Mat &input, cv::Mat &output, const float sigmaC, const float epsilon, const int filterType=TYPE_FAST)"
.br
.ti -1c
.RI "cv::Mat \fBtrilateralFilter\fP (cv::Mat &input, const float sigmaC, const float epsilon, const int filterType=TYPE_FAST)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file openCVtrilateralFilter\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for targeter from the source code\&.
