.TH "qimage_to_mat_cpy_policy" 3 "Fri Mar 17 2017" "Version 1" "targeter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qimage_to_mat_cpy_policy
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static cv::Mat \fBstart\fP (QImage const &img, int format)"
.br
.in -1c
.SH "Detailed Description"
.PP 
copy QImage into cv::Mat 
.PP
Definition at line 23 of file opencvtoqt\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for targeter from the source code\&.
