.TH "SliderProxy" 3 "Fri Mar 17 2017" "Version 1" "targeter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SliderProxy
.SH SYNOPSIS
.br
.PP
.PP
Inherits QProxyStyle\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBpixelMetric\fP (PixelMetric metric, const QStyleOption *option=0, const QWidget *widget=0) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file superslider\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for targeter from the source code\&.
