.TH "SliderEventFilter" 3 "Fri Mar 17 2017" "Version 1" "targeter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SliderEventFilter
.SH SYNOPSIS
.br
.PP
.PP
Inherits QObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSliderEventFilter\fP (\fBSuperSlider\fP *_grandParent)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fBeventFilter\fP (QObject *obj, QEvent *event)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file superslider\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SliderEventFilter::SliderEventFilter (\fBSuperSlider\fP * _grandParent)\fC [inline]\fP"
Constructor 
.PP
Definition at line 50 of file superslider\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for targeter from the source code\&.
