.TH "Ui::MainWindow" 3 "Fri Mar 17 2017" "Version 1" "targeter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::MainWindow
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_MainWindow\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 567 of file ui_mainwindow\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for targeter from the source code\&.
