.TH "Ui::SettingsDialog" 3 "Fri Mar 17 2017" "Version 1" "targeter" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::SettingsDialog
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_SettingsDialog\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 437 of file ui_settingsdialog\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for targeter from the source code\&.
